name: Backend Test
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Clean npm cache
          
        run: npm cache clean --force

      - name: Install dependencies in backend
        run: |
          cd backend
          npm install
          
      - name: Create service account JSON file
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        run: |
          mkdir -p backend/src
          echo '{' > backend/src/tempestmap-f0234-firebase-adminsdk-fbsvc-cb8db3f6e9.json
          echo '  "type": "service_account",' >> backend/src/tempestmap-f0234-firebase-adminsdk-fbsvc-cb8db3f6e9.json
          echo '  "project_id": "tempestmap-f0234",' >> backend/src/tempestmap-f0234-firebase-adminsdk-fbsvc-cb8db3f6e9.json
          echo '  "private_key_id": "cb8db3f6e98e0bc166291808c78a0684a57a18e2",' >> backend/src/tempestmap-f0234-firebase-adminsdk-fbsvc-cb8db3f6e9.json
          echo '  "private_key": "'"$PRIVATE_KEY"'",' >> backend/src/tempestmap-f0234-firebase-adminsdk-fbsvc-cb8db3f6e9.json
          echo '  "client_email": "firebase-adminsdk-fbsvc@tempestmap-f0234.iam.gserviceaccount.com",' >> backend/src/tempestmap-f0234-firebase-adminsdk-fbsvc-cb8db3f6e9.json
          echo '  "client_id": "107007959838485127095",' >> backend/src/tempestmap-f0234-firebase-adminsdk-fbsvc-cb8db3f6e9.json
          echo '  "auth_uri": "https://accounts.google.com/o/oauth2/auth",' >> backend/src/tempestmap-f0234-firebase-adminsdk-fbsvc-cb8db3f6e9.json
          echo '  "token_uri": "https://oauth2.googleapis.com/token",' >> backend/src/tempestmap-f0234-firebase-adminsdk-fbsvc-cb8db3f6e9.json
          echo '  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",' >> backend/src/tempestmap-f0234-firebase-adminsdk-fbsvc-cb8db3f6e9.json
          echo '  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/firebase-adminsdk-fbsvc%40tempestmap-f0234.iam.gserviceaccount.com",' >> backend/src/tempestmap-f0234-firebase-adminsdk-fbsvc-cb8db3f6e9.json
          echo '  "universe_domain": "googleapis.com"' >> backend/src/tempestmap-f0234-firebase-adminsdk-fbsvc-cb8db3f6e9.json
          echo '}' >> backend/src/tempestmap-f0234-firebase-adminsdk-fbsvc-cb8db3f6e9.json
      
      - name: Run Jest tests in backend
        run: |
          cd backend
          npm test
